icl_prompt = '''
Context:
- British voters elected to leave the European Union. UK Independence Party leader Nigel Farage admitted a key Leave campaign promise about redirecting EU funds to the national health system was inaccurate. Residents of Cornwall worried about losing promised EU subsidies. The British pound plummeted, global stocks tanked, and some voters regretted their decision, with some claiming they thought they were lodging a protest vote and didn't think Brexit would actually happen. Over three million Brits called for a do-over. Critics say Prime Minister David Cameron initiated the referendum due to a political bind. Political scientist David A. Bell argues referendums on technical issues undermine democratic institutions. He also notes referendums can lead to policies that are hard to dislodge and undermine the legitimacy of legislatures. Brexit supporters cast the vote as one of fundamental sovereignty. Martin Kettle argued Brexit should be a referendum on referendums.

- Intelligence exchanges primarily occur between individual nation states in Europe, outside of EU jurisdiction. The UK possesses unique intelligence capabilities due to its partnerships with the U.S. and the "Five Eyes" alliance. The UK drafted the EU Counter Terrorism Strategy in 2005 and influenced EU initiatives like the Europol Counter Terrorism Centre (CTC) and the PNRD. The UK's intelligence-led counter terrorism policing concept integrates intelligence agencies with the police. The EAW has increased extradition speed between EU states, and Europol/Eurojust facilitate police/judicial cooperation. The UK joined the Schengen Information System for information sharing. Post-Brexit, EU states are expected to continue counter-terrorism cooperation with the UK, and the UK will likely seek access to EU law enforcement databases. The UK will presumably remain in the non-EU Counter Terrorist Group (CTG). The UK will need to negotiate new arrangements, potentially through bilateral agreements. Officials acknowledge potential limits compared to the pre-Brexit situation due to precedents. The negotiation process may hinder counter-terrorism efforts. The UK government will aim to retain close counter-terrorism cooperation. Brexit could exacerbate tensions in Northern Ireland and may encourage violent republican dissidents if they can build grassroots support.

- On June 23, U.K. citizens will vote on whether the United Kingdom should remain in or leave the European Union (EU). In 2013, Prime Minister David Cameron pledged a referendum on EU membership if his Conservative Party won the next election. The party won, and the referendum date was set in February. Cameron's attempt to renegotiate the U.K.'s EU membership terms failed, leading to the "Brexit" campaign. The nation divided into "remain" and "leave" camps. The EU has 28 member states and represents a large economic output. Member nations contribute to the EU budget. EU initiatives have funded projects in the U.K. The EU ensures the free movement of people, goods, services, and money within its single market. Polls show a close split in public opinion. Registration for the referendum caused the government website to crash and spurred an extension of the initial deadline. A transition out of the EU could take years if U.K. citizens vote "leave".

- On June 24, 2016, British Prime Minister David Cameron stated that the British people voted to leave the European Union and their will must be respected. Cameron announced he would resign as Prime Minister because the country requires fresh leadership. He will remain as Prime Minister for the next three months. The Cabinet will meet on Monday, and the Governor of the Bank of England is making a statement. A negotiation with the European Union will need to begin under a new Prime Minister, who will decide when to trigger Article 50. Cameron will attend the European Council next week to explain the decision. Cameron stated that Britain can survive outside the European Union and he will do everything he can to help this country succeed. Cameron walked back to Number 10 with his wife Samantha.

- The UK voted to leave the EU in a June 23 referendum by a margin of 52% to 48%. UK public opinion of the EU has been less favorable than that of other EU members for nearly a decade. A Pew Research Center survey indicated that some other EU countries share the UK's desire for a less centralized Europe. The UK public perceived the EU as inefficient, intrusive, and mishandling key issues like refugees and the economy. 65% of the British public desired the return of some EU powers to London prior to the referendum. The Brexit vote exposed a division between Scotland, which voted to remain in the EU by 62% to 38%, and the rest of the UK. Scotland and the rest of the UK also diverge on economic and immigration threat perceptions. Other EU member states largely viewed Brexit as detrimental to the EU. A majority in Greece and pluralities in other EU nations favor returning some EU power to their national governments.

- The UK voted to leave the European Union, triggering British Prime Minister David Cameron's resignation. The Brexit vote caused market plunges globally. Cameron announced his intention to stand down, wanting a pro-exit leader by October. Boris Johnson is tipped as Cameron’s likely successor. Nicola Sturgeon said the Scottish government will prepare legislation for a new independence referendum. Sinn Fein called for a referendum on Irish unity. European leaders expressed regret, with some fearing a domino effect and others congratulating the UK. UKIP leader Nigel Farage called the EU a "dying" institution. President Obama said the US-UK relationship would endure. NATO reassured that the UK would remain a strong ally. The Dow Jones Industrial Average fell 611 points and the British pound plunged to its lowest level since 1985.

- The United Kingdom held a referendum on June 23 to decide whether to leave (Brexit) or remain in the European Union (EU). Stanford scholar Christophe Crombez recommended the UK remain, arguing that leaving would negatively impact the UK, the EU, and global politics, and only create an illusion of sovereignty. Arguments for leaving include saving taxpayer money, avoiding unwanted EU laws, and controlling migration. Crombez refuted these, stating the UK benefits more from the EU market than its contributions, and that post-Brexit, the UK would still need to comply with EU rules to trade, and immigration requirements would still be imposed. Leaving the EU would negatively affect UK trade and GDP, create uncertainty, and consume resources in break-up negotiations. The EU would be less impacted economically, but the idea of European unification would be damaged. Brexit could trigger other countries to hold referendums and could lead to the break-up of the UK, with Scotland potentially leaving to stay in the EU.

- U.K. voters decided to leave the European Union, leading Prime Minister Cameron to announce his resignation. The EU referendum vote was 52 percent in favor of leaving. Northern Ireland and Scotland voted to remain, raising the possibility of the United Kingdom breaking apart. Cameron said the country requires fresh leadership and will resign before October. The process of leaving the EU will likely take years. The British pound plunged in value, and global stock markets plummeted. The referendum's outcome came as a shock to many. Sinn Fein called for a referendum on unification with Ireland. Scotland may hold a second referendum on independence. The EU assembly will hold an emergency session. Eurosceptic parties in Sweden, Denmark, and France called for EU membership referenda in their own nations. The Dow dropped approximately 500 points. Trump stated that the "place is going wild over the vote. They took their country back, just like we will take America back." Obama stated "the people of the United Kingdom have spoken, and we respect their decision."


Question: Which of the following options are the causes of the event 'British voters decided to leave the European Union (Brexit), with 52% voting to leave.'?
Options:
A. Prime Minister David Cameron pledged a referendum on EU membership in 2013 if his Conservative Party won the next election.
B. Cameron's attempt to renegotiate the U.K.'s EU membership terms failed.
C. The information provided is insufficient to determine the cause.
D. The United Kingdom held a referendum on whether to leave or remain in the European Union on June 23.

Please select all correct answers based on the context above. Respond with comma-separated letters only (e.g., "A,B").
Output: "A,B,D"

Context:
- Former Japanese Prime Minister Shinzo Abe was assassinated at a campaign rally. Security arrested the suspected gunman, Tetsuya Yamagami. Yamagami fired two shots at Abe; the second shot hit Abe's chest and neck. Abe died several hours later. Yamagami attacked Abe due to Abe's association with a group Yamagami hated. Tributes were given by President Biden, Secretary of State Antony Blinken, Indian Prime Minister Narendra Modi, Russian President Vladimir Putin, and former Australian Prime Minister Tony Abbott. Abe worked to build up Japan's military and reform the economy. Abe failed to revise Japan's constitution but passed legislation allowing Japan's military to expand operations overseas. Abe was a critic of China and called on the US to give Taiwan assurances of help in the event of an attack by China.

- Former Japanese Prime Minister Shinzo Abe was shot while delivering a campaign speech in Nara. The attack occurred at approximately 11:30 a.m. before upper house elections. Abe collapsed, bleeding from the neck and chest. He was taken to a hospital in cardiac arrest and pronounced dead at 5:03 p.m. due to excessive bleeding; a bullet reached his heart. Tetsuya Yamagami, 41, was arrested for attempted murder; police recovered a gun, possibly homemade. Witnesses reported hearing two gunshots. World leaders, including Donald Trump, Emmanuel Macron, and Narendra Modi, condemned the attack.

- In the early 2000s, Shinzo Abe was the deputy chief cabinet secretary. In 2002, Abe handled arrangements for a summit between Junichiro Koizumi and Kim Jong Il in Pyongyang. In 2006, Abe became the youngest prime minister in postwar Japan. In 2012, Abe returned to office and later became the longest-serving prime minister. During his tenure, Abe implemented "Abenomics," and the stock market increased but economic inequality widened. Yoshihide Suga succeeded Abe in September 2020. Abe met with Donald Trump and Vladimir Putin, and in 2014, he met with Xi Jinping. After his death, Abe was celebrated for strengthening the defense alliance with the United States. Abe wanted to revise the Japanese Constitution but died still pushing for it.

- On July 8, 2022, former Japanese Prime Minister Shinzo Abe was murdered while campaigning in Nara. Doctors attempted to save Abe's life after he was shot, but he remained comatose. Prime Minister Fumio Kishida condemned the attack. Abe had a bullet wound on his neck and subcutaneous bleeding on his chest. Witnesses saw a man firing twice at Abe from behind. Security officers detained the attacker, Tetsuya Yamagami, and seized his handmade gun. Yamagami is believed to be a former member of Japan’s Maritime Self-Defense Forces. Explosives were found at his home. World leaders expressed shock and condemned the murder, warning of attacks on supporters of democracy. The incident has drawn comparisons to pre-World War II political violence in Japan, including the assassinations of PM Hirobumi Ito and Finance Minister Korekiyo Takahashi. Past post-WW2 political violence includes the stabbing of Inejiro Asanuma in 1960, the shooting of Iccho Ito in 2007 and the stabbing of Koki Ishii.

- Shinzo Abe recognized China's challenge to the American-led system and aimed to counter it. He reinterpreted Japan's constitution in 2014 to allow the military to operate overseas and equipped it accordingly. Abe coined the phrase "a free and open Indo-Pacific" to shift the focus from the "Asia-Pacific" concept centered on China. This involved including India as a counterweight and emphasizing the South China Sea. He promoted the Quadrilateral Security Dialogue (Quad) between Japan, India, the US, and Australia, facing pushback from China. Abe outlined his vision for a "free and open Indo-Pacific" in 2016, based on the rule of law, economic prosperity, and peace. The Quad was reborn, and the US adopted the "free and open Indo-Pacific" concept. After Abe's death, tributes highlighted his influence, particularly his restructuring of Japan's foreign policy in response to China's rise. The phrase "a free and open Indo-Pacific" is now prevalent in US policy and military statements.

- Shinzo Abe, Japan's former prime minister, was assassinated while giving a campaign speech in Nara. The suspected gunman was arrested at the scene with a handmade gun. Abe, 67, was shot, collapsed, and was bleeding from the chest. Videos of the assassination circulated on social media, prompting social media companies to remove harmful content. Abe was a polarizing figure known for revitalizing Japan’s economy and his revisionist views of World War II.

- Shinzo Abe, former Japanese prime minister, was assassinated at a campaign rally. Abe was shot multiple times from behind while speaking at a rally in Nara. Abe, a nationalist, aimed to change Japan’s pacifist character. He increased diplomacy with Israel, starting with a 2014 visit to Tokyo by Benjamin Netanyahu, which increased trade. Abe offered to host a peace summit in 2017 and visited Jerusalem in 2018.

- Shinzo Abe, former Prime Minister of Japan, was assassinated during a campaign rally in Nara, Japan. The shooting involved a gun, rare in Japan due to stringent firearm laws. Gun violence is almost unheard-of in Japan, with only one firearm-related death in 2021. The shooter used a handmade gun, which was seized along with several others at his home. Japan's firearms laws are strict, requiring a 12-step process to purchase a gun. Political assassinations were common before WWII, but rare since; the last killing of a national political figure was in 1960. Light police protection at political events allowed the shooter unobstructed access. The incident has shocked Japan and raised questions about the country's safety and political future.


Question: Which of the following options are the causes of the event 'Shinzo Abe collapsed; Shinzo Abe; Bleeding from neck and chest after being shot.'?
Options:
A. Abe became prime minister of Japan in 2006.
B. Shinzo Abe was murdered while campaigning in Nara on July 8, 2022.
C. The information provided is insufficient to determine the cause.
D. Tetsuya Yamagami fired two shots at Shinzo Abe, hitting his chest and neck.

Please select all correct answers based on the context above. Respond with comma-separated letters only (e.g., "A,B").
Output: "B,D"

Context:
- President Yoon Suk Yeol declared martial law, accusing the opposition of undermining the democratic system. The martial-law command suspended the legislature and controlled the media. Opposition parties and leaders of the ruling party denounced the action. Lawmakers unanimously annulled martial law. Protesters gathered, and some blocked soldiers from entering parliament. The U.S. and UK issued travel advisories. Opposition parties filed a motion to impeach President Yoon. Yoon's aides offered to resign. The U.S. stated that ending martial law was a crucial step.

- President Yoon Suk-yeol faces a second impeachment motion in the National Assembly after declaring martial law on December 3, triggering protests. The motion requires 200 votes to pass. Some legislators from Yoon’s party support the motion. Yoon refuses to resign. If impeached, Yoon's powers will be suspended, and the prime minister will become acting president. The opposition is considering impeaching the Prime Minister as well, in which case the deputy prime minister for the economy would take over as acting president. The Constitutional Court will review the case; six of nine justices must support the motion for it to be upheld. Currently only six justices sit on the bench. The court must decide within 180 days. Yoon may argue martial law was within his powers. If the court upholds the impeachment, Yoon will be removed and an election will be held within 60 days. If rejected, Yoon will be reinstated. Yoon also faces criminal investigations, including charges of insurrection. Yoon could potentially be arrested.

- South Korea's parliament impeached President Yoon Suk Yeol after his martial law attempt. This followed his ruling party withdrawing support due to his refusal to resign. Yoon is suspended from power pending a Constitutional Court decision. Following the vote, Yoon conceded temporarily but vowed to continue his journey. Prime Minister Han Duck-soo became acting president. The impeachment vote followed Yoon's martial law declaration on December 3, sending soldiers to parliament. Opposition parties had previously attempted impeachment. Yoon defended his martial law decision in a speech. The leader of Yoon's party then backed impeachment. Protests occurred for and against Yoon. The Constitutional Court will review the impeachment. Investigations into Yoon have begun, including a police raid of the presidential office. Former defense minister Kim Yong-hyun was detained. Yoon's justice minister and police chief have already been impeached. Yoon's administration also faced probes by police, parliament, prosecutors and the anti-corruption body on treason allegations. Special Warfare Command Commander Kwak Jong-geun testified that he received a direct order from President Yoon to break the doors of the National Assembly and drag out the lawmakers, but he did not comply.

- South Korean legislators launched an impeachment push against President Yoon Suk Yeol, accusing him of declaring martial law to evade investigations into himself and his family. Lawmakers overturned Yoon's martial law declaration, tussling with troops to enter the National Assembly and vote it down. Opposition legislators filed an impeachment motion accusing Yoon of violating the constitution and law with the martial law imposition. Lawmakers presented the impeachment motion to parliament. The governing People Power Party opposes the motion, but the opposition Democratic Party needs some governing party support to pass it. Impeachment requires a two-thirds majority. The governing party leader called for accountability and demanded an explanation from the president. If impeached, Yoon will be temporarily stripped of presidential authority. Several senior officials offered their resignations. Prime Minister Han Duck-soo pledged to continue serving. The Korean Confederation of Trade Unions called for a strike until Yoon's resignation. Yoon lifted the martial law order hours after the initial declaration, claiming it was necessary to defend against North Korean threats and accusing the opposition of paralyzing the government. Lawmakers passed a motion forcing Yoon to reverse the order after tussling with soldiers to enter parliament. A Democratic Party leader accused Yoon of treason.

- Tens of thousands of South Korean protesters demonstrated near the National Assembly in Seoul, calling for President Yoon Suk Yeol's removal. Baek Jae Gil adapted "Feliz Navidad" into a protest anthem, "Impeachment is the answer," and performed it outside the National Assembly after Yoon's declaration of martial law. The song spread online. Baek Jae Gil, a musician, has been protesting for decades, noting a shift toward more peaceful demonstrations. He was inspired by past protests, including those against President Park Geun-hye's impeachment. He wrote his "Feliz Navidad" adaptation in 2022 after protests grew following a crowd crush. He faced copyright issues with a satirical video earlier in the year. Last week, he performed his anthem at the National Assembly and again at last Saturday’s protests.

- Tens of thousands protested near South Korea's National Assembly, calling for President Yoon Suk Yeol's impeachment as lawmakers voted on the motion. The impeachment motion failed. Protests intensified following Yoon's declaration of martial law. A smaller group of Yoon's supporters gathered in Seoul.


Question: Which of the following options are the causes of the event 'Yoon faces criminal investigations including insurrection charges, potentially leading to arrest.'?
Options:
A. Martial-law command suspended the legislature and controlled the media.
B. South Korean parliament impeached President Yoon Suk Yeol following his martial law attempt.
C. Prime Minister Han Duck-soo became acting president after Yoon's impeachment.
D. Impeachment Vote: Lawmakers voted on a motion to impeach President Yoon Suk Yeol; the motion failed.

Please select all correct answers based on the context above. Respond with comma-separated letters only (e.g., "A,B").
Output: "A,B,C"

Context:
{context}

Question: {question}
Options:
A. {option_A}
B. {option_B}
C. {option_C}
D. {option_D}

Please select all correct answers based on the context above. Respond with comma-separated letters only (e.g., "A,B").
Output: 
'''

icl_cot_prompt = '''
Context:
- British voters elected to leave the European Union. UK Independence Party leader Nigel Farage admitted a key Leave campaign promise about redirecting EU funds to the national health system was inaccurate. Residents of Cornwall worried about losing promised EU subsidies. The British pound plummeted, global stocks tanked, and some voters regretted their decision, with some claiming they thought they were lodging a protest vote and didn't think Brexit would actually happen. Over three million Brits called for a do-over. Critics say Prime Minister David Cameron initiated the referendum due to a political bind. Political scientist David A. Bell argues referendums on technical issues undermine democratic institutions. He also notes referendums can lead to policies that are hard to dislodge and undermine the legitimacy of legislatures. Brexit supporters cast the vote as one of fundamental sovereignty. Martin Kettle argued Brexit should be a referendum on referendums.

- Intelligence exchanges primarily occur between individual nation states in Europe, outside of EU jurisdiction. The UK possesses unique intelligence capabilities due to its partnerships with the U.S. and the "Five Eyes" alliance. The UK drafted the EU Counter Terrorism Strategy in 2005 and influenced EU initiatives like the Europol Counter Terrorism Centre (CTC) and the PNRD. The UK's intelligence-led counter terrorism policing concept integrates intelligence agencies with the police. The EAW has increased extradition speed between EU states, and Europol/Eurojust facilitate police/judicial cooperation. The UK joined the Schengen Information System for information sharing. Post-Brexit, EU states are expected to continue counter-terrorism cooperation with the UK, and the UK will likely seek access to EU law enforcement databases. The UK will presumably remain in the non-EU Counter Terrorist Group (CTG). The UK will need to negotiate new arrangements, potentially through bilateral agreements. Officials acknowledge potential limits compared to the pre-Brexit situation due to precedents. The negotiation process may hinder counter-terrorism efforts. The UK government will aim to retain close counter-terrorism cooperation. Brexit could exacerbate tensions in Northern Ireland and may encourage violent republican dissidents if they can build grassroots support.

- On June 23, U.K. citizens will vote on whether the United Kingdom should remain in or leave the European Union (EU). In 2013, Prime Minister David Cameron pledged a referendum on EU membership if his Conservative Party won the next election. The party won, and the referendum date was set in February. Cameron's attempt to renegotiate the U.K.'s EU membership terms failed, leading to the "Brexit" campaign. The nation divided into "remain" and "leave" camps. The EU has 28 member states and represents a large economic output. Member nations contribute to the EU budget. EU initiatives have funded projects in the U.K. The EU ensures the free movement of people, goods, services, and money within its single market. Polls show a close split in public opinion. Registration for the referendum caused the government website to crash and spurred an extension of the initial deadline. A transition out of the EU could take years if U.K. citizens vote "leave".

- On June 24, 2016, British Prime Minister David Cameron stated that the British people voted to leave the European Union and their will must be respected. Cameron announced he would resign as Prime Minister because the country requires fresh leadership. He will remain as Prime Minister for the next three months. The Cabinet will meet on Monday, and the Governor of the Bank of England is making a statement. A negotiation with the European Union will need to begin under a new Prime Minister, who will decide when to trigger Article 50. Cameron will attend the European Council next week to explain the decision. Cameron stated that Britain can survive outside the European Union and he will do everything he can to help this country succeed. Cameron walked back to Number 10 with his wife Samantha.

- The UK voted to leave the EU in a June 23 referendum by a margin of 52% to 48%. UK public opinion of the EU has been less favorable than that of other EU members for nearly a decade. A Pew Research Center survey indicated that some other EU countries share the UK's desire for a less centralized Europe. The UK public perceived the EU as inefficient, intrusive, and mishandling key issues like refugees and the economy. 65% of the British public desired the return of some EU powers to London prior to the referendum. The Brexit vote exposed a division between Scotland, which voted to remain in the EU by 62% to 38%, and the rest of the UK. Scotland and the rest of the UK also diverge on economic and immigration threat perceptions. Other EU member states largely viewed Brexit as detrimental to the EU. A majority in Greece and pluralities in other EU nations favor returning some EU power to their national governments.

- The UK voted to leave the European Union, triggering British Prime Minister David Cameron's resignation. The Brexit vote caused market plunges globally. Cameron announced his intention to stand down, wanting a pro-exit leader by October. Boris Johnson is tipped as Cameron’s likely successor. Nicola Sturgeon said the Scottish government will prepare legislation for a new independence referendum. Sinn Fein called for a referendum on Irish unity. European leaders expressed regret, with some fearing a domino effect and others congratulating the UK. UKIP leader Nigel Farage called the EU a "dying" institution. President Obama said the US-UK relationship would endure. NATO reassured that the UK would remain a strong ally. The Dow Jones Industrial Average fell 611 points and the British pound plunged to its lowest level since 1985.

- The United Kingdom held a referendum on June 23 to decide whether to leave (Brexit) or remain in the European Union (EU). Stanford scholar Christophe Crombez recommended the UK remain, arguing that leaving would negatively impact the UK, the EU, and global politics, and only create an illusion of sovereignty. Arguments for leaving include saving taxpayer money, avoiding unwanted EU laws, and controlling migration. Crombez refuted these, stating the UK benefits more from the EU market than its contributions, and that post-Brexit, the UK would still need to comply with EU rules to trade, and immigration requirements would still be imposed. Leaving the EU would negatively affect UK trade and GDP, create uncertainty, and consume resources in break-up negotiations. The EU would be less impacted economically, but the idea of European unification would be damaged. Brexit could trigger other countries to hold referendums and could lead to the break-up of the UK, with Scotland potentially leaving to stay in the EU.

- U.K. voters decided to leave the European Union, leading Prime Minister Cameron to announce his resignation. The EU referendum vote was 52 percent in favor of leaving. Northern Ireland and Scotland voted to remain, raising the possibility of the United Kingdom breaking apart. Cameron said the country requires fresh leadership and will resign before October. The process of leaving the EU will likely take years. The British pound plunged in value, and global stock markets plummeted. The referendum's outcome came as a shock to many. Sinn Fein called for a referendum on unification with Ireland. Scotland may hold a second referendum on independence. The EU assembly will hold an emergency session. Eurosceptic parties in Sweden, Denmark, and France called for EU membership referenda in their own nations. The Dow dropped approximately 500 points. Trump stated that the "place is going wild over the vote. They took their country back, just like we will take America back." Obama stated "the people of the United Kingdom have spoken, and we respect their decision."


Question: Which of the following options are the causes of the event 'British voters decided to leave the European Union (Brexit), with 52% voting to leave.'?
Options:
A. Prime Minister David Cameron pledged a referendum on EU membership in 2013 if his Conservative Party won the next election.
B. Cameron's attempt to renegotiate the U.K.'s EU membership terms failed.
C. The information provided is insufficient to determine the cause.
D. The United Kingdom held a referendum on whether to leave or remain in the European Union on June 23.

Output: 
Rationale: The decision by British voters to leave the EU, as evidenced by the 52% vote, was made possible by the referendum held on June 23rd (Option D). This referendum itself was a direct result of Prime Minister David Cameron's 2013 pledge to hold one if his party won the election (Option A). A key factor contributing to the 'leave' sentiment and campaign was Cameron's failed attempt to renegotiate the U.K.'s EU membership terms (Option B). Option C is incorrect because sufficient information is provided in the context to identify A, B, and D as causes. 
Final Answer: A,B,D

Context:
- Former Japanese Prime Minister Shinzo Abe was assassinated at a campaign rally. Security arrested the suspected gunman, Tetsuya Yamagami. Yamagami fired two shots at Abe; the second shot hit Abe's chest and neck. Abe died several hours later. Yamagami attacked Abe due to Abe's association with a group Yamagami hated. Tributes were given by President Biden, Secretary of State Antony Blinken, Indian Prime Minister Narendra Modi, Russian President Vladimir Putin, and former Australian Prime Minister Tony Abbott. Abe worked to build up Japan's military and reform the economy. Abe failed to revise Japan's constitution but passed legislation allowing Japan's military to expand operations overseas. Abe was a critic of China and called on the US to give Taiwan assurances of help in the event of an attack by China.

- Former Japanese Prime Minister Shinzo Abe was shot while delivering a campaign speech in Nara. The attack occurred at approximately 11:30 a.m. before upper house elections. Abe collapsed, bleeding from the neck and chest. He was taken to a hospital in cardiac arrest and pronounced dead at 5:03 p.m. due to excessive bleeding; a bullet reached his heart. Tetsuya Yamagami, 41, was arrested for attempted murder; police recovered a gun, possibly homemade. Witnesses reported hearing two gunshots. World leaders, including Donald Trump, Emmanuel Macron, and Narendra Modi, condemned the attack.

- In the early 2000s, Shinzo Abe was the deputy chief cabinet secretary. In 2002, Abe handled arrangements for a summit between Junichiro Koizumi and Kim Jong Il in Pyongyang. In 2006, Abe became the youngest prime minister in postwar Japan. In 2012, Abe returned to office and later became the longest-serving prime minister. During his tenure, Abe implemented "Abenomics," and the stock market increased but economic inequality widened. Yoshihide Suga succeeded Abe in September 2020. Abe met with Donald Trump and Vladimir Putin, and in 2014, he met with Xi Jinping. After his death, Abe was celebrated for strengthening the defense alliance with the United States. Abe wanted to revise the Japanese Constitution but died still pushing for it.

- On July 8, 2022, former Japanese Prime Minister Shinzo Abe was murdered while campaigning in Nara. Doctors attempted to save Abe's life after he was shot, but he remained comatose. Prime Minister Fumio Kishida condemned the attack. Abe had a bullet wound on his neck and subcutaneous bleeding on his chest. Witnesses saw a man firing twice at Abe from behind. Security officers detained the attacker, Tetsuya Yamagami, and seized his handmade gun. Yamagami is believed to be a former member of Japan’s Maritime Self-Defense Forces. Explosives were found at his home. World leaders expressed shock and condemned the murder, warning of attacks on supporters of democracy. The incident has drawn comparisons to pre-World War II political violence in Japan, including the assassinations of PM Hirobumi Ito and Finance Minister Korekiyo Takahashi. Past post-WW2 political violence includes the stabbing of Inejiro Asanuma in 1960, the shooting of Iccho Ito in 2007 and the stabbing of Koki Ishii.

- Shinzo Abe recognized China's challenge to the American-led system and aimed to counter it. He reinterpreted Japan's constitution in 2014 to allow the military to operate overseas and equipped it accordingly. Abe coined the phrase "a free and open Indo-Pacific" to shift the focus from the "Asia-Pacific" concept centered on China. This involved including India as a counterweight and emphasizing the South China Sea. He promoted the Quadrilateral Security Dialogue (Quad) between Japan, India, the US, and Australia, facing pushback from China. Abe outlined his vision for a "free and open Indo-Pacific" in 2016, based on the rule of law, economic prosperity, and peace. The Quad was reborn, and the US adopted the "free and open Indo-Pacific" concept. After Abe's death, tributes highlighted his influence, particularly his restructuring of Japan's foreign policy in response to China's rise. The phrase "a free and open Indo-Pacific" is now prevalent in US policy and military statements.

- Shinzo Abe, Japan's former prime minister, was assassinated while giving a campaign speech in Nara. The suspected gunman was arrested at the scene with a handmade gun. Abe, 67, was shot, collapsed, and was bleeding from the chest. Videos of the assassination circulated on social media, prompting social media companies to remove harmful content. Abe was a polarizing figure known for revitalizing Japan’s economy and his revisionist views of World War II.

- Shinzo Abe, former Japanese prime minister, was assassinated at a campaign rally. Abe was shot multiple times from behind while speaking at a rally in Nara. Abe, a nationalist, aimed to change Japan’s pacifist character. He increased diplomacy with Israel, starting with a 2014 visit to Tokyo by Benjamin Netanyahu, which increased trade. Abe offered to host a peace summit in 2017 and visited Jerusalem in 2018.

- Shinzo Abe, former Prime Minister of Japan, was assassinated during a campaign rally in Nara, Japan. The shooting involved a gun, rare in Japan due to stringent firearm laws. Gun violence is almost unheard-of in Japan, with only one firearm-related death in 2021. The shooter used a handmade gun, which was seized along with several others at his home. Japan's firearms laws are strict, requiring a 12-step process to purchase a gun. Political assassinations were common before WWII, but rare since; the last killing of a national political figure was in 1960. Light police protection at political events allowed the shooter unobstructed access. The incident has shocked Japan and raised questions about the country's safety and political future.


Question: Which of the following options are the causes of the event 'Shinzo Abe collapsed; Shinzo Abe; Bleeding from neck and chest after being shot.'?
Options:
A. Abe became prime minister of Japan in 2006.
B. Shinzo Abe was murdered while campaigning in Nara on July 8, 2022.
C. The information provided is insufficient to determine the cause.
D. Tetsuya Yamagami fired two shots at Shinzo Abe, hitting his chest and neck.

Output: Rationale: The event, Shinzo Abe collapsing and bleeding from the neck and chest after being shot, was directly caused by Tetsuya Yamagami firing two shots at him, with the second shot hitting his chest and neck (Option D). This shooting was the core act of his murder while campaigning in Nara on July 8, 2022 (Option B). Abe's earlier prime ministership in 2006 (Option A) is historical context and not a direct cause of this specific medical event. Option C is incorrect as the context provides clear causes. 
Final Answer: B,D

Context:
- President Yoon Suk Yeol declared martial law, accusing the opposition of undermining the democratic system. The martial-law command suspended the legislature and controlled the media. Opposition parties and leaders of the ruling party denounced the action. Lawmakers unanimously annulled martial law. Protesters gathered, and some blocked soldiers from entering parliament. The U.S. and UK issued travel advisories. Opposition parties filed a motion to impeach President Yoon. Yoon's aides offered to resign. The U.S. stated that ending martial law was a crucial step.

- President Yoon Suk-yeol faces a second impeachment motion in the National Assembly after declaring martial law on December 3, triggering protests. The motion requires 200 votes to pass. Some legislators from Yoon’s party support the motion. Yoon refuses to resign. If impeached, Yoon's powers will be suspended, and the prime minister will become acting president. The opposition is considering impeaching the Prime Minister as well, in which case the deputy prime minister for the economy would take over as acting president. The Constitutional Court will review the case; six of nine justices must support the motion for it to be upheld. Currently only six justices sit on the bench. The court must decide within 180 days. Yoon may argue martial law was within his powers. If the court upholds the impeachment, Yoon will be removed and an election will be held within 60 days. If rejected, Yoon will be reinstated. Yoon also faces criminal investigations, including charges of insurrection. Yoon could potentially be arrested.

- South Korea's parliament impeached President Yoon Suk Yeol after his martial law attempt. This followed his ruling party withdrawing support due to his refusal to resign. Yoon is suspended from power pending a Constitutional Court decision. Following the vote, Yoon conceded temporarily but vowed to continue his journey. Prime Minister Han Duck-soo became acting president. The impeachment vote followed Yoon's martial law declaration on December 3, sending soldiers to parliament. Opposition parties had previously attempted impeachment. Yoon defended his martial law decision in a speech. The leader of Yoon's party then backed impeachment. Protests occurred for and against Yoon. The Constitutional Court will review the impeachment. Investigations into Yoon have begun, including a police raid of the presidential office. Former defense minister Kim Yong-hyun was detained. Yoon's justice minister and police chief have already been impeached. Yoon's administration also faced probes by police, parliament, prosecutors and the anti-corruption body on treason allegations. Special Warfare Command Commander Kwak Jong-geun testified that he received a direct order from President Yoon to break the doors of the National Assembly and drag out the lawmakers, but he did not comply.

- South Korean legislators launched an impeachment push against President Yoon Suk Yeol, accusing him of declaring martial law to evade investigations into himself and his family. Lawmakers overturned Yoon's martial law declaration, tussling with troops to enter the National Assembly and vote it down. Opposition legislators filed an impeachment motion accusing Yoon of violating the constitution and law with the martial law imposition. Lawmakers presented the impeachment motion to parliament. The governing People Power Party opposes the motion, but the opposition Democratic Party needs some governing party support to pass it. Impeachment requires a two-thirds majority. The governing party leader called for accountability and demanded an explanation from the president. If impeached, Yoon will be temporarily stripped of presidential authority. Several senior officials offered their resignations. Prime Minister Han Duck-soo pledged to continue serving. The Korean Confederation of Trade Unions called for a strike until Yoon's resignation. Yoon lifted the martial law order hours after the initial declaration, claiming it was necessary to defend against North Korean threats and accusing the opposition of paralyzing the government. Lawmakers passed a motion forcing Yoon to reverse the order after tussling with soldiers to enter parliament. A Democratic Party leader accused Yoon of treason.

- Tens of thousands of South Korean protesters demonstrated near the National Assembly in Seoul, calling for President Yoon Suk Yeol's removal. Baek Jae Gil adapted "Feliz Navidad" into a protest anthem, "Impeachment is the answer," and performed it outside the National Assembly after Yoon's declaration of martial law. The song spread online. Baek Jae Gil, a musician, has been protesting for decades, noting a shift toward more peaceful demonstrations. He was inspired by past protests, including those against President Park Geun-hye's impeachment. He wrote his "Feliz Navidad" adaptation in 2022 after protests grew following a crowd crush. He faced copyright issues with a satirical video earlier in the year. Last week, he performed his anthem at the National Assembly and again at last Saturday’s protests.

- Tens of thousands protested near South Korea's National Assembly, calling for President Yoon Suk Yeol's impeachment as lawmakers voted on the motion. The impeachment motion failed. Protests intensified following Yoon's declaration of martial law. A smaller group of Yoon's supporters gathered in Seoul.


Question: Which of the following options are the causes of the event 'Yoon faces criminal investigations including insurrection charges, potentially leading to arrest.'?
Options:
A. Martial-law command suspended the legislature and controlled the media.
B. South Korean parliament impeached President Yoon Suk Yeol following his martial law attempt.
C. Prime Minister Han Duck-soo became acting president after Yoon's impeachment.
D. Impeachment Vote: Lawmakers voted on a motion to impeach President Yoon Suk Yeol; the motion failed.

Output: Rationale: Yoon is facing criminal investigations including insurrection charges. These stem from his declaration of martial law, under which the martial-law command suspended the legislature and controlled the media (Option A); such actions are grounds for insurrection charges. If the parliament indeed impeached Yoon following this attempt (Option B, based on one part of the context), this formal denouncement and process would naturally lead to or be concurrent with criminal investigations. Consequently, the Prime Minister becoming acting president after Yoon's impeachment (Option C) would mean Yoon is suspended, facilitating unhindered investigations. Option D (impeachment failed) contradicts the scenario where B and C are causative factors for the investigations proceeding due to a successful impeachment. Thus, considering the context supporting a successful impeachment for options B and C to be causative, A, B, and C contribute to the investigations. 
Final Answer: A,B,C

Context:
{context}

Question: {question}
Options:
A. {option_A}
B. {option_B}
C. {option_C}
D. {option_D}
Output:
'''